### ISSUE TITLE
Revise the Spinx workflow

### ISSUE THREAD

**Issue by brad-t-moore** [KitwareMedical/ITKPOCUS#12]
I'm having difficulty getting the out-of- `docs/` .md files to render images correctly.  I've tried using the `myst-parser` and `m2r2` but the documentation isn't great and they simply aren't working.

**Comment by thewtex** [comment]
@jcfr may have some tips

**Comment by jcfr** [comment]
The pull request https://github.com/BICCN/cell-locator/pull/177  from @allemangD  added support for building documentation by integrating MyST with sphinx. It was adapted from prior work done by @lassoan in Slicer in https://github.com/Slicer/Slicer/pull/5662 .

Let us know if you have any questions,
